---
sidebar: sidebar 
permalink: concept-onprem-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: 'BlueXP peut détecter les clusters ONTAP s"exécutant sur des contrôleurs AFF/FAS et sur ONTAP Select. L"ajout de systèmes ONTAP sur site à BlueXP vous permet de gérer l"ensemble de vos ressources de stockage et de données à partir d"une seule interface.' 
---
= Découvrez la gestion des clusters ONTAP sur site dans BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP peut détecter les clusters ONTAP s'exécutant sur des contrôleurs AFF/FAS et sur ONTAP Select. L'ajout de systèmes ONTAP sur site à BlueXP vous permet de gérer l'ensemble de vos ressources de stockage et de données à partir d'une seule interface.



== Caractéristiques

* Gestion des volumes NFS et CIFS
* Procédez à une gestion avancée avec ONTAP System Manager
* Assurez l'observabilité et les performances avec l'analyse et le contrôle de BlueXP
* Utilisez les services BlueXP pour répliquer, sauvegarder, analyser, classer et hiérarchiser vos données
* Affichez des informations sur l'état des contrats matériels et logiciels dans le portefeuille digital BlueXP




== Le coût

Un coût peut être associé, mais cela dépend des éléments suivants :

* Que vous déployiez un connecteur pour détecter et gérer vos clusters.
+
Vous pouvez installer le connecteur dans le cloud ou sur site.

* Que vous utilisiez les services BlueXP, tels que la sauvegarde et la restauration, le Tiering et la classification.

