---
sidebar: sidebar 
permalink: concept-aiq-digital-advisor.html 
keywords: concepts, active iq digital advisor, ontap 
summary: 'BlueXP Digital Advisor vous permet d"optimiser les opérations, la sécurité et les performances de vos clusters ONTAP.' 
---
= Optimisez les clusters à l'aide de BlueXP Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP Digital Advisor vous permet d'optimiser les opérations, la sécurité et les performances de vos clusters ONTAP.



== Caractéristiques

Grâce à BlueXP Digital Advisor, vous pouvez afficher l'état global de votre système de stockage, des informations générales sur son intégrité, l'inventaire, la planification, les mises à niveau, ainsi que des informations exploitables au niveau de la liste de suivi.

* Analyse et optimisation de l'état de vos systèmes de stockage
* Obtenez des informations sur tous les risques encourus par vos systèmes de stockage et sur les actions réalisées pour limiter les risques
* Analysez les performances de vos périphériques de stockage en consultant le format graphique des données de performances
* Découvrez en détail les systèmes dont la capacité a dépassé 90 % ou approchent 90 %
* Obtenez des informations sur le matériel et les logiciels qui ont expiré ou sont à court d'expiration dans les 6 mois à venir
* Mettez à niveau le logiciel de votre système de stockage et mettez à jour le firmware de votre ONTAP à l'aide d'Ansible




== Systèmes ONTAP pris en charge

Digital Advisor fournit des informations sur tous les systèmes ONTAP sur site et les systèmes Cloud Volumes ONTAP associés à votre compte sur le site de support NetApp (NSS).



== Plus d'informations

https://["Documentation de Digital Advisor"^]
