---
settings:
  name: On-prem ONTAP clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Documentation sur le cluster ONTAP sur site
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrir les clusters ONTAP
      url: "/task-discovering-ontap.html"
  - title: Gestion des clusters ONTAP sur site
    entries:
    - title: Gestion des volumes ONTAP sur site
      url: "/task-provisioning-ontap.html"
    - title: Administration à l'aide de System Manager
      url: "/task-administer-advanced-view.html"
    - title: Optimisez les clusters avec Digital Advisor
      url: "/concept-aiq-digital-advisor.html"
    - title: Suppression d'un environnement de travail ONTAP sur site
      url: "/task-remove-on-prem.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Affichez les clusters sur site découverts et non découverts
      url: task-discovering-ontap.html#viewing-discovered-and-undiscovered-on-prem-clusters
    - title: Découvrir les clusters ONTAP
      url: task-discovering-ontap.html
    - title: Nouveautés
      url: whats-new.html
  - title: Gestion des clusters ONTAP sur site
    links:
    - title: Créer des volumes
      url: task-provisioning-ontap.html
    - title: Téléchargez le nouveau firmware des tiroirs et des disques
      url: task-managing-ontap.html#downloading-new-disk-and-shelf-firmware
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
