---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limites connues
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.



== Clusters non pris en charge

Les clusters ONTAP sur site configurés avec l'authentification SAML ne sont pas pris en charge par BlueXP.



== Limites de System Manager

Les fonctionnalités suivantes de System Manager ne sont pas prises en charge par BlueXP :

* Configuration du cluster
+
Une fois que vous avez défini l'adresse IP de gestion et configuré le mot de passe d'administration sur un cluster ONTAP sur site, vous pouvez détecter le cluster dans BlueXP.

* Contrôle d'accès basé sur des rôles (connecteur uniquement)
+
Le contrôle d'accès basé sur des rôles dans System Manager n'est pas pris en charge lors de la découverte et de la gestion d'un cluster ONTAP sur site à l'aide d'un connecteur. Vous êtes invité à saisir vos informations d'identification administrateur lors du processus de détection. Ces identifiants sont utilisés pour toutes les actions effectuées depuis System Manager.

+
Avec l'option de découverte directe, vous êtes invité à vous connecter avec vos identifiants ONTAP à chaque fois que vous ouvrez l'environnement de travail.

* Activation de la sauvegarde et de la restauration BlueXP (Cloud Backup)
+
La version du cluster doit être 9.13.1 pour activer la sauvegarde et la restauration BlueXP depuis System Manager.

+
Si vous avez _NOT_ découvert un cluster à l'aide d'un connecteur, vous ne pouvez pas utiliser System Manager (vue avancée) pour activer la sauvegarde et la restauration. Cependant, vous pouvez activer la sauvegarde et la restauration sur un cluster sur site directement à partir de BlueXP. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html["Découvrez comment démarrer"^]

* Mises à niveau à la demande
+
Les mises à niveau à la demande du firmware et du logiciel ne sont pas disponibles si la version du cluster est ONTAP 9.9.1 ou antérieure.

+
Si vous ne possédez pas de connecteur, vous ne pouvez pas effectuer de mises à jour à partir de votre ordinateur local, uniquement à partir d'un serveur auquel vous pouvez accéder à l'aide de BlueXP.

* Recherche globale
* Paramètres de l'interface utilisateur

